  spring.jpa.properties.hibernate.default_schema=capability
    spring.flyway.default-schema=capability
spring:
  jpa:
    properties:
      hibernate:
        default_schema: bpmn
  flyway:
    default-schema: bpmn
camunda.bpm.admin-user:
  id: beeatlas
  password: beeatlas
camunda:
  bpm:
    auto-deployment-enabled: true
integration:
  capability-server-url: https://capability-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  dashboard-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru