camunda:
  bpm:
    admin-user:
      id: beeatlas
      password: beeatlas
    data-source: camundaDataSource
    database:
      schema-update: true
integration:
  capability-server-url: https://capability-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  dashboard-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
queue:
  package-queue:
    name: package_queue

spring:
  datasource:
    git:
      hikari:
        maximum-pool-size: 2
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

