camunda:
  bpm:
    admin-user:
      id: beeatlas
      password: beeatlas
    data-source: camundaDataSource
    database:
      schema-update: true
    job-execution:
        enabled: true

integration:
  capability-server-url: https://capability-backend-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
  dashboard-server-url: https://dashboard-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
queue:
  package-queue:
    name: package_queue

spring:
  datasource:
    git:
      hikari:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        url: ${SPRING_DATASOURCE_GIT_URL}
        username: ${SPRING_DATASOURCE_GIT_USERNAME}
        password: ${SPRING_DATASOURCE_GIT_PASSWORD}
        maximum-pool-size: 2
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    processes:
      driver-class-name: org.postgresql.Driver

  jpa:
    processes:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
          format_sql: true
          show_sql: true
          default_schema: processes

  flyway:
    enabled: true
    default-schema: processes
    schemas: processes
    baseline-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration