UPDATE processes.status_process
SET "sequence"=5
WHERE id=2;
UPDATE processes.status_process
SET "sequence"=5
WHERE id=3;
UPDATE processes.status_process
SET "sequence"=6
WHERE id=4;
UPDATE processes.status_process
SET "sequence"=6
WHERE id=5;
UPDATE processes.status_process
SET "sequence"=6
WHERE id=6;
UPDATE processes.status_process
SET "sequence"=9
WHERE id=7;
UPDATE processes.status_process
SET "sequence"=9
WHERE id=8;
UPDATE processes.status_process
SET "sequence"=10
WHERE id=9;
UPDATE processes.status_process
SET "sequence"=10
WHERE id=10;
UPDATE processes.status_process
SET "sequence"=10
WHERE id=11;
UPDATE processes.status_process
SET "sequence"=11
WHERE id=12;
UPDATE processes.status_process
SET "sequence"=11
WHERE id=13;
UPDATE processes.status_process
SET "sequence"=12
WHERE id=14;
UPDATE processes.status_process
SET "sequence"=12
WHERE id=15;
UPDATE processes.status_process
SET "sequence"=3
WHERE id=16;
UPDATE processes.status_process
SET "sequence"=3
WHERE id=17;
UPDATE processes.status_process
SET "sequence"=7
WHERE id=18;
UPDATE processes.status_process
SET "sequence"=7
WHERE id=19;
UPDATE processes.status_process
SET "sequence"=15
WHERE id=21;
UPDATE processes.status_process
SET "sequence"=15
WHERE id=22;
